// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5GTGQO3qWszRvmklaPUb8BljcbFrJpk',
    appId: '1:84874629948:web:1690f573c0f66ab1258439',
    messagingSenderId: '84874629948',
    projectId: 'flutter-demo-985d0',
    authDomain: 'flutter-demo-985d0.firebaseapp.com',
    storageBucket: 'flutter-demo-985d0.firebasestorage.app',
    measurementId: 'G-SWJ55J1MVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78drqgqrJVe7Se6XqORurTvTIWVLqLVE',
    appId: '1:84874629948:android:eee1524022e9a921258439',
    messagingSenderId: '84874629948',
    projectId: 'flutter-demo-985d0',
    storageBucket: 'flutter-demo-985d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCARJa1r_W7JSmzBdcxQkqbHuoMXrCGN0I',
    appId: '1:84874629948:ios:4bc071ad5db4557c258439',
    messagingSenderId: '84874629948',
    projectId: 'flutter-demo-985d0',
    storageBucket: 'flutter-demo-985d0.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCARJa1r_W7JSmzBdcxQkqbHuoMXrCGN0I',
    appId: '1:84874629948:ios:4bc071ad5db4557c258439',
    messagingSenderId: '84874629948',
    projectId: 'flutter-demo-985d0',
    storageBucket: 'flutter-demo-985d0.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_5GTGQO3qWszRvmklaPUb8BljcbFrJpk',
    appId: '1:84874629948:web:e6a1713c3f489fef258439',
    messagingSenderId: '84874629948',
    projectId: 'flutter-demo-985d0',
    authDomain: 'flutter-demo-985d0.firebaseapp.com',
    storageBucket: 'flutter-demo-985d0.firebasestorage.app',
    measurementId: 'G-9M386TZW6D',
  );
}
